### ISSUE TITLE
AGASC 1.8

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#153]
### Tasks
- [x] Do analysis to figure out how to use GAIA data
- [x] Come up with a magnitude calibration for GAIA matches
- [x] Figure out a strategy for duplicate stars
- [x] Finish AGASC 1.8 calibration after removing duplicates
- [x] Develop comprehensive validation strategy (which will include notebooks and processing output to be used later to support the FSDS and ECR) -- some of this is on Jean to do functional independent verification notebooks
- [x] Make an AGASC 1.8
    - [x] Make h5 files
      - [x] make agasc1p8.h5 - note that this should have indexes on RA, DEC, and AGASC_ID
      - [x] make proseco_agasc_1p8.h5 - (question from Jean -- will we need the 1p8 proseco agasc to have all the stars that were in proseco 1p7 agasc + whatever stars match the proseco filter?)
      - [x] Hopefully move to a HEALpix implementation https://github.com/sot/agasc/issues/152
   - [x] Make FITS files for DS
      - [x] Use FITS files to do functional independent review of median offsets / improved positions. - Jean
   - [x] Verify files - show in a notebook
- [x] Hand off FITS files to DS
- [x] Update any calling code in ska3 as needed to use proseco_agasc.h5 instead of proseco_agasc_1p7.h5
   - [x] proseco - (at least the proseco_agasc_1p7.h5)
   - [x] starcheck - (at least the proseco_agasc_1p7.h5)
   - [x] agasc
   - [x] kadi
- [x] Update any calling code in fot matlab tools as needed
   - [x] this could be the new filename and could be required with HEALpix update
           It looks like the direct use of proseco_agasc_1p7 in MissionScheduling/stars/StarCatalog/get_agasc_cone.m can be overriden with env var AGASC_HDF5_FILE .  It also looks like the matlab tools complain about the missing agasc FITS files (if I delete the directory) but I don't think they are actually used?  Still need to check with James and Mark.
- [x] Update syncing process to sync new proseco AGASC
   - [x] ska_sync
- [x] Create plots and promotion package for AGASC ECRs for FOT and SOT review
- [x] Bring to FDB
- [x] Promote for star selection
