### ISSUE TITLE
AGASC 1.8 Post promotion

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#186]
### Tasks
- [] Update the distances h5 file for find_attitude https://github.com/sot/find_attitude/issues/20
- [] Update documentation and archive 1.7 docs (but leave available)
- [] Link AGASC 1.8 summary page from sot github docs and move out of jgonzale area
- [] Update MTA page with AGASC 1.8 info and FDB presentation and star working group page
- [] Ask Arcops to update https://cxc.harvard.edu/agasc
- [] Ask SOT MP to update https://icxc.harvard.edu/mp/html/agasc.html
- [] Review bad star lists to see if some can be "redeemed" with AGASC 1.8
